



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author delacal_23
 */


public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */


    
    
    
    
    public Formulario() {
        initComponents();
        //Ubicar Formulario en el centro de la pantalla.
        this.setLocationRelativeTo(null);
//        imprimirNulo();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        teclas = new javax.swing.JPanel();
        imprimirForm = new javax.swing.JButton();
        limpiarForm = new javax.swing.JButton();
        titulo = new javax.swing.JPanel();
        tituloText = new javax.swing.JLabel();
        datos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        serialNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        partNumber = new javax.swing.JTextField();
        codigoTienda = new javax.swing.JComboBox<>();
        numeroInci = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        incidencia = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        incidenciaText = new javax.swing.JTextArea();
        solucion = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        solucionText = new javax.swing.JTextArea();
        accesorios = new javax.swing.JPanel();
        accOtros = new javax.swing.JCheckBox();
        accBateria = new javax.swing.JCheckBox();
        accCable = new javax.swing.JCheckBox();
        accCargador = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePiezas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parte de HP");
        setBackground(new java.awt.Color(0, 153, 255));
        setResizable(false);

        teclas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 0, 204))); // NOI18N

        imprimirForm.setForeground(new java.awt.Color(0, 153, 255));
        imprimirForm.setText("Imprimir");
        imprimirForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imprimirFormMousePressed(evt);
            }
        });

        limpiarForm.setForeground(new java.awt.Color(0, 153, 255));
        limpiarForm.setText("Limpiar");
        limpiarForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                limpiarFormMousePressed(evt);
            }
        });

        javax.swing.GroupLayout teclasLayout = new javax.swing.GroupLayout(teclas);
        teclas.setLayout(teclasLayout);
        teclasLayout.setHorizontalGroup(
            teclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teclasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limpiarForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imprimirForm)
                .addContainerGap())
        );
        teclasLayout.setVerticalGroup(
            teclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teclasLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(teclasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiarForm)
                    .addComponent(imprimirForm))
                .addGap(10, 10, 10))
        );

        titulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tituloText.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        tituloText.setForeground(new java.awt.Color(0, 153, 255));
        tituloText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/HP_logo_2012_opt.png"))); // NOI18N
        tituloText.setText("Parte de Reparaciones HP");

        datos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 153, 255))); // NOI18N
        datos.setForeground(new java.awt.Color(0, 153, 255));

        jLabel2.setText("Nombre Cliente:");

        jLabel3.setText("Modelo (P/N):");

        jLabel4.setText("Serial S/N:");

        codigoTienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "SACAR", "DIG" }));

        numeroInci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroInciKeyTyped(evt);
            }
        });

        fecha.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout datosLayout = new javax.swing.GroupLayout(datos);
        datos.setLayout(datosLayout);
        datosLayout.setHorizontalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(datosLayout.createSequentialGroup()
                        .addComponent(codigoTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroInci))
                    .addGroup(datosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(partNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(datosLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        datosLayout.setVerticalGroup(
            datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosLayout.createSequentialGroup()
                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosLayout.createSequentialGroup()
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(codigoTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(datosLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numeroInci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(datosLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3))))
                    .addGroup(datosLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(serialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        incidencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Incidencia:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 153, 255))); // NOI18N

        incidenciaText.setColumns(20);
        incidenciaText.setRows(5);
        jScrollPane4.setViewportView(incidenciaText);

        javax.swing.GroupLayout incidenciaLayout = new javax.swing.GroupLayout(incidencia);
        incidencia.setLayout(incidenciaLayout);
        incidenciaLayout.setHorizontalGroup(
            incidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incidenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        incidenciaLayout.setVerticalGroup(
            incidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incidenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        solucion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solucion:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 153, 255))); // NOI18N

        solucionText.setColumns(20);
        solucionText.setRows(5);
        jScrollPane3.setViewportView(solucionText);

        javax.swing.GroupLayout solucionLayout = new javax.swing.GroupLayout(solucion);
        solucion.setLayout(solucionLayout);
        solucionLayout.setHorizontalGroup(
            solucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );
        solucionLayout.setVerticalGroup(
            solucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        accesorios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Accesorios:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 153, 255))); // NOI18N

        accOtros.setText("Otros -->");

        accBateria.setText("Bateria");

        accCable.setText("Cable de corriente");

        accCargador.setText("Cargador (Transformador)");

        jTextField1.setText(" ");

        javax.swing.GroupLayout accesoriosLayout = new javax.swing.GroupLayout(accesorios);
        accesorios.setLayout(accesoriosLayout);
        accesoriosLayout.setHorizontalGroup(
            accesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accesoriosLayout.createSequentialGroup()
                .addGroup(accesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(accesoriosLayout.createSequentialGroup()
                        .addComponent(accBateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accCable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accCargador))
                    .addGroup(accesoriosLayout.createSequentialGroup()
                        .addComponent(accOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        accesoriosLayout.setVerticalGroup(
            accesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accesoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accBateria)
                    .addGroup(accesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(accCargador)
                        .addComponent(accCable)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accOtros)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Piezas"));

        tablePiezas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Pieza"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePiezas);
        if (tablePiezas.getColumnModel().getColumnCount() > 0) {
            tablePiezas.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/LogoHead_Outsourcing.gif"))); // NOI18N
        jLabel1.setText(" ");

        javax.swing.GroupLayout tituloLayout = new javax.swing.GroupLayout(titulo);
        titulo.setLayout(tituloLayout);
        tituloLayout.setHorizontalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tituloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(incidencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tituloLayout.createSequentialGroup()
                                .addComponent(solucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(accesorios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tituloLayout.createSequentialGroup()
                        .addComponent(tituloText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tituloLayout.setVerticalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloText)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(solucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accesorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(teclas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teclas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    //bloquea el boton iprimir si esta todo sin rellenar.
//    private void imprimirNulo(){
//        if (numeroInci.getText().equals("") &&  nombreCliente.getText().equals("") && 
//            partNumber.getText().equals("") && serialNumber.getText().equals("") && 
//            incidenciaText.getText().equals("") && solucionText.getText().equals("") ){
//            
//            imprimirForm.setEnabled(false);
//        }
//        
//          else { 
//              imprimirForm.setEnabled(true);       
//        }
//}
    private void imprimirFormMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimirFormMousePressed
//         variables 
//        String incidencia, nombreClien, modelo, serial, problemaIncidencia, solucion;
//        incidencia = numeroInci.getText();
//        nombreClien = nombreCliente.getText();
//        modelo = partNumber.getText();
//        serial = serialNumber.getText();
//        problemaIncidencia = incidenciaText.getText();
//        solucion = solucionText.getText();
//        
//       Codigo para datos  generales, comprueba que lo datos estan escritos
//       if (numeroInci.getText().equals("")){
//           JOptionPane.showMessageDialog(null, "Por favor ingresa Numero de incidencia" );
//       }
//       if (nombreCliente.getText().equals("")){
//           JOptionPane.showMessageDialog(null, "Por favor ingresa Nombre cliente" );
//       }
//       if (partNumber.getText().equals("")){
//           JOptionPane.showMessageDialog(null, "Por favor ingresa P/N" );
//       }
//       if (serialNumber.getText().equals("")){
//           JOptionPane.showMessageDialog(null, "Por favor ingresa S/N" );
//       }
//       if (incidenciaText.getText().equals("")){
//           JOptionPane.showMessageDialog(null, "Por favor ingrese el problema del cliente" );
//       }
//       if (solucionText.getText().equals("")){
//           JOptionPane.showMessageDialog(null, "Por favor ingrese la solucion realizada" );
//       }
           
       
    }//GEN-LAST:event_imprimirFormMousePressed

    private void limpiarFormMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarFormMousePressed
     
      // Limpiar formulario  *Faltan checkBOX y Fecha*
      numeroInci.setText(null);
      nombreCliente.setText(null);
      partNumber.setText(null);
      serialNumber.setText(null);
      incidenciaText.setText(null);
      solucionText.setText(null);
      codigoTienda.setSelectedIndex(0); 
    }//GEN-LAST:event_limpiarFormMousePressed

    //Limitamos que el numero de incidnecia no pueda Contener Letras.
    private void numeroInciKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroInciKeyTyped
        char inci = evt.getKeyChar();
        if (inci < '0' || inci > '9'){
            evt.consume();
        }
    }//GEN-LAST:event_numeroInciKeyTyped

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Formulario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox accBateria;
    private javax.swing.JCheckBox accCable;
    private javax.swing.JCheckBox accCargador;
    private javax.swing.JCheckBox accOtros;
    private javax.swing.JPanel accesorios;
    private javax.swing.JComboBox<String> codigoTienda;
    private javax.swing.JPanel datos;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton imprimirForm;
    private javax.swing.JPanel incidencia;
    private javax.swing.JTextArea incidenciaText;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limpiarForm;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTextField numeroInci;
    private javax.swing.JTextField partNumber;
    private javax.swing.JTextField serialNumber;
    private javax.swing.JPanel solucion;
    private javax.swing.JTextArea solucionText;
    private javax.swing.JTable tablePiezas;
    private javax.swing.JPanel teclas;
    private javax.swing.JPanel titulo;
    private javax.swing.JLabel tituloText;
    // End of variables declaration//GEN-END:variables
}
